@gambling_HostAddress = http://localhost:5045

###Register your player first
POST {{gambling_HostAddress}}/register/
Content-Type: application/json

{
    "email": "gentgovori@gmail.com",
    "password": "123456789Aa#"
}


###Login using that player and get the token
#@name login
POST {{gambling_HostAddress}}/login
Content-Type: application/json


{
    "email": "gentgovori@gmail.com",
    "password": "123456789Aa#"
}

###To play the game, add the bearer token you get from the login request 
POST {{gambling_HostAddress}}/gambleyourlifeaway
Content-Type: application/json
Authorization: Bearer 

{
    "points" : 100,
    "number" : 4
}
